# Practice

1. You want to create a function that generates an array of n random real numbers between a and b. Which of the following code snippets accomplishes this?

2. Given the following NumPy array:

    np_arr = np.array([5, 7, -2, 3])
    Which of the following code snippets will correctly transform np_arr into the array shown below?
    
    1. np_arr.reshape(2, 2)
    2. np_arr.reshape(2, 2).T
    3. np_arr.reshape(2, 2).transpose()
    4. np_arr.T.reshape(2, 2)

In [1]:
import numpy as np
import pandas as pd
np_arr = np.array([5, 7, -2, 3])

In [2]:
np_arr.reshape(2, 2)

array([[ 5,  7],
       [-2,  3]])

In [3]:
np_arr.reshape(2, 2).T

array([[ 5, -2],
       [ 7,  3]])

In [4]:
np_arr.reshape(2, 2).transpose()

array([[ 5, -2],
       [ 7,  3]])

In [5]:
np_arr.T.reshape(2, 2)

array([[ 5,  7],
       [-2,  3]])

3. Consider the array shown below:

    np_arr = np.array([[100, 200, 300], [-150, -250, -350]])
     
    
    What do the following operations do?
    1. np_arr.reshape(-1)
    2. np_arr.reshape(-1, 1)

In [6]:
np_arr = np.array([[100, 200, 300], [-150, -250, -350]])
np_arr

array([[ 100,  200,  300],
       [-150, -250, -350]])

In [7]:
np_arr.reshape(-1)

array([ 100,  200,  300, -150, -250, -350])

In [8]:
np_arr.reshape(-1, 1)

array([[ 100],
       [ 200],
       [ 300],
       [-150],
       [-250],
       [-350]])

In [9]:
np_arr.reshape(2, -1)

array([[ 100,  200,  300],
       [-150, -250, -350]])

4. Consider the array shown below:

    np_arr = np.array([[1, 5], [-5, 2], [3, 1]])
 

What sequence of operations can be performed on np_arr to transform it into the desired array shown below:

    np.array([[1, -5], [5, 2], [4, -6]])

In [10]:
np_arr = np.array([[1, 5], [-5, 2], [3, 1]])
np_arr

array([[ 1,  5],
       [-5,  2],
       [ 3,  1]])

In [11]:
np_arr = np.delete(np_arr, 2, 0)
np_arr

array([[ 1,  5],
       [-5,  2]])

In [12]:
res = np.append(np_arr, [[4,6]]).reshape(3,2)
res

array([[ 1,  5],
       [-5,  2],
       [ 4,  6]])

5. Suppose you have an array img with an original shape of 32×32×3. If you want to find the mean of the array along its second (middle) dimension, what will be the resulting shape after the mean operation?

In [13]:
# Great question!

# You have:

# img.shape = (32, 32, 3)
# This means:
    # 32 rows
    # 32 columns
    # 3 channels (e.g., RGB)

# Now you're taking the mean along axis 1 (the second dimension, i.e., columns):

# mean_img = np.mean(img, axis=1)
# What happens?
# You're reducing the 32 columns into a single value per row and channel

# So the axis 1 is collapsed

# Resulting shape:

# (32, 3)
# 32 rows (same)

# 3 channels (same)

# Columns averaged out

6. What is the output of the following code snippet?

len(df_cars[(df_cars['carbody'] == 'convertible') & (df_cars['citympg'] > 20) & (df_cars['price'] < 15000)])

In [14]:
df_cars = pd.read_csv('data/cars_dataset.csv')
df_cars.head()

car_ID  symboling                   carname doornumber      carbody  \
0       1          3        alfa-romero giulia        two  convertible   
1       2          3       alfa-romero stelvio        two  convertible   
2       3          1  alfa-romero Quadrifoglio        two    hatchback   
3       4          2               audi 100 ls       four        sedan   
4       5          2                audi 100ls       four        sedan   

  enginelocation  wheelbase  carlength  carwidth  carheight  ...  \
0          front       88.6      168.8      64.1       48.8  ...   
1          front       88.6      168.8      64.1       48.8  ...   
2          front       94.5      171.2      65.5       52.4  ...   
3          front       99.8      176.6      66.2       54.3  ...   
4          front       99.4      176.6      66.4       54.3  ...   

   cylindernumber enginesize  boreratio  stroke  compressionratio  horsepower  \
0            four        130       3.47    2.68               9.0         111   
1            four        130       3.47    2.68               9.0         111   
2             six        152       2.68    3.47               9.0         154   
3            four        109       3.19    3.40              10.0         102   
4            five        136       3.19    3.40               8.0         115   

   peakrpm  citympg  highwaympg    price  
0     5000       21          27  13495.0  
1     5000       21          27  16500.0  
2     5000       19          26  16500.0  
3     5500       24          30  13950.0  
4     5500       18          22  17450.0  

[5 rows x 21 columns]

In [15]:
len(df_cars[(df_cars['carbody'] == 'convertible') & (df_cars['citympg'] > 20) & (df_cars['price'] < 15000)])

2

7. If you take the mean rating as a popularity measure, which one of the following can be used to find the name of the most popular movie?


    df_movies.describe().transpose()['mean'].idxmax()
    
    df_movies.describe().loc['mean'].idxmax()
    
    df_movies.mean().max()
    
    df_movies.describe().transpose().max()['mean']

In [16]:
df_movies = pd.read_csv('data/User_Movie_Ratings.csv')
df_movies


User  Thor  Justice League  Spiderman  The Notebook  Casablanca  \
0      Arnold     6               5          6             4           5   
1         Ben     9              10          8             3           1   
2   Catherine    10               8          9             5           6   
3       Disha     6               7          7            10           9   
4      Euclid     7               4          3             5           8   
5     Farhaan     6               5          9             4           4   
6      Gaurav     8               8          9             3           1   
7     Hilbert     6               5          8             6           5   
8      Indira    10               7          9             5           6   
9       Jason    10               9          9             7           4   
10      Kenny     3               2          5             9           8   
11    Lambert     5               6          4            10           9   
12     Manish     7               6          6             5           6   
13       Niti     3               3          2             7           8   
14     Oliver     4               5          4             2           2   
15     Pranav     8               9          8             4           1   
16      Qader     8               7          8             5           4   
17       Ravi     8               7          9            10           9   
18    Sushant     5               8          6             1           1   
19    Tavneet     1               1          4             7           6   

    Beauty and the Beast  Dolittle  The Kissing Booth  Annabelle  Insidious  
0                      4         9                  8          2          1  
1                      1         2                  5          7          8  
2                      7         8                  5          9          9  
3                     10         7                  6          5          6  
4                      5         9                 10          8          7  
5                      7         9                  9          5          4  
6                      1         7                  5          7          7  
7                      8        10                  9          2          1  
8                      4         2                  1          6          8  
9                      6         1                  1          5          4  
10                     8         4                  1          1          3  
11                     8         1                  2         10          9  
12                     8         7                  6          6          5  
13                     7        10                  9          4          5  
14                     1         7                  6          1          2  
15                     2         3                  1          8          7  
16                     6         3                  4          6          5  
17                     8         8                  8          9         10  
18                     2         7                  8          6          5  
19                     8         9                 10          1          5

In [17]:
df_movies.describe()

Thor  Justice League  Spiderman  The Notebook  Casablanca  \
count  20.00000        20.00000  20.000000     20.000000   20.000000   
mean    6.50000         6.10000   6.650000      5.600000    5.150000   
std     2.50263         2.38195   2.300458      2.643761    2.852054   
min     1.00000         1.00000   2.000000      1.000000    1.000000   
25%     5.00000         5.00000   4.750000      4.000000    3.500000   
50%     6.50000         6.50000   7.500000      5.000000    5.500000   
75%     8.00000         8.00000   9.000000      7.000000    8.000000   
max    10.00000        10.00000   9.000000     10.000000    9.000000   

       Beauty and the Beast   Dolittle  The Kissing Booth  Annabelle  \
count             20.000000  20.000000          20.000000   20.00000   
mean               5.550000   6.150000           5.700000    5.40000   
std                2.855742   3.116594           3.180533    2.81724   
min                1.000000   1.000000           1.000000    1.00000   
25%                3.500000   3.000000           3.500000    3.50000   
50%                6.500000   7.000000           6.000000    6.00000   
75%                8.000000   9.000000           8.250000    7.25000   
max               10.000000  10.000000          10.000000   10.00000   

       Insidious  
count  20.000000  
mean    5.550000  
std     2.605157  
min     1.000000  
25%     4.000000  
50%     5.000000  
75%     7.250000  
max    10.000000

In [18]:
df_movies.describe().transpose()

count  mean       std  min   25%  50%   75%   max
Thor                   20.0  6.50  2.502630  1.0  5.00  6.5  8.00  10.0
Justice League         20.0  6.10  2.381950  1.0  5.00  6.5  8.00  10.0
Spiderman              20.0  6.65  2.300458  2.0  4.75  7.5  9.00   9.0
The Notebook           20.0  5.60  2.643761  1.0  4.00  5.0  7.00  10.0
Casablanca             20.0  5.15  2.852054  1.0  3.50  5.5  8.00   9.0
Beauty and the Beast   20.0  5.55  2.855742  1.0  3.50  6.5  8.00  10.0
Dolittle               20.0  6.15  3.116594  1.0  3.00  7.0  9.00  10.0
The Kissing Booth      20.0  5.70  3.180533  1.0  3.50  6.0  8.25  10.0
Annabelle              20.0  5.40  2.817240  1.0  3.50  6.0  7.25  10.0
Insidious              20.0  5.55  2.605157  1.0  4.00  5.0  7.25  10.0

In [19]:
df_movies.describe().transpose()['mean'].idxmax()

'Spiderman'

In [20]:
df_movies.describe().loc['mean'].idxmax()

'Spiderman'

In [21]:
df_movies.describe().transpose().max()['mean']

np.float64(6.65)

How can you determine the number of cars with two doors or four doors in the df_cars dataframe?

In [22]:
df_cars['doornumber'].value_counts()

doornumber
four    75
two     72
Name: count, dtype: int64

8. Let’s say you want to replace movie ratings above 5 with ‘good’ and everything else with ‘bad’ without modifying the original dataframe in place. 

What is the correct way of achieving this task?



In [ ]:
def corrections(row):
    return 'good' if strtoint(row) > 5 else 'bad'
new_df = df_movies.map(corrections)