In [2]:
# list
# tuples
# sets 
# dict
# strings
# if elif else
# def | lambda
# for while

In [4]:
# NumPy -> Numerical Python!
# array -> fast, multidimensional objects used for numerical calcualtions!

In [6]:
import numpy  as np
import pandas as pd

In [8]:
arr_1d = np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

In [10]:
print(arr_1d)

[1 2 3 4 5]


In [12]:
arr_1d = np.array((1,2,3,4,5))
arr_1d

array([1, 2, 3, 4, 5])

In [14]:
type(arr_1d)

numpy.ndarray

In [16]:
arr_1d.ndim #dimension of the array!

1

In [20]:
# 2d array : 
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr_2d.ndim

2

In [26]:
arr_2d.shape #rows,columns!

(2, 3)

In [28]:
# zero!
arr_zero = np.zeros(5)
arr_zero

array([0., 0., 0., 0., 0.])

In [30]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [34]:
# np.ones
arr_1 = np.ones(10)
arr_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [40]:
# Creating two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

In [42]:
arr1 + arr2 #addition!

array([ 6,  8, 10, 12])

In [44]:
arr1 - arr2 #sub

array([-4, -4, -4, -4])

In [46]:
arr1*arr2

array([ 5, 12, 21, 32])

In [48]:
arr1/arr2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [50]:
arr = np.array([5,10,15,20,25])
arr

array([ 5, 10, 15, 20, 25])

In [52]:
np.min(arr)

5

In [54]:
np.max(arr)

25

In [56]:
np.mean(arr)

15.0

In [58]:
np.median(arr)

15.0

In [60]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [64]:
# no. of elemets - 12 | as of now its 1d array
# reshape array to other shapes , which other shapes are applicable?
# 2x6 | 6x2 | 3x4 | 4x3 | 12*1 | 1*12 - CAN
# 1x8 , 10x1 - CANNOT (Total elements - 12)

In [66]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [68]:
arr.reshape(3,3) #error

ValueError: cannot reshape array of size 12 into shape (3,3)

In [70]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [72]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [74]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [78]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [82]:
arr = np.array([5,12,1,0,3])
arr

array([ 5, 12,  1,  0,  3])

In [84]:
arr[0]

5

In [86]:
arr[3] # 3rd index ; 4th element

0

In [88]:
# what is an identity matrix?

In [90]:
# nxn array diagnol with 1 as diagnol

In [92]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [96]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])