In [2]:
import numpy as np

In [19]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
print("The first element is ", arr1[0])
print("The first element is ", arr1[-1])
print("The first element is ", arr1[1])
print("The first element is ", arr1[4])

The first element is  1
The first element is  6
The first element is  2
The first element is  5


## Slicing ##

In [20]:
arr1[2:5:1]

array([3, 4, 5])

In [21]:
arr1[:3]

array([1, 2, 3])

In [22]:
arr1[:2:]

array([1, 2])

In [23]:
arr1[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Define 2D Array ##

2D array also nown as array

In [30]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
arr2.shape

(3, 3)

In [32]:
arr2.size

9

In [33]:
arr2.ndim

2

In [34]:
len(arr2)

3

## Zero Matrix ##

In [36]:
np.zeros((4,9), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
np.ones((4,9), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

## Full Matrix" ##

In [39]:
fullmatrice = np.full((3,4),fill_value=2)
print(fullmatrice)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Identity matrices ##

In [40]:
print(np.eye(5,dtype=int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [42]:
print(np.diag([10,21,13,4,5,6]))

[[10  0  0  0  0  0]
 [ 0 21  0  0  0  0]
 [ 0  0 13  0  0  0]
 [ 0  0  0  4  0  0]
 [ 0  0  0  0  5  0]
 [ 0  0  0  0  0  6]]


## Arrange function ##

In [43]:
#range(0,10) -> 1,2,3,4,5,6,7,8,9,10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
#default step size is a int , can be float as well eg .5
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [46]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [47]:
np.arange(0,10,.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

## Reshaping a array ##

In [50]:
#size of array before and after reshaping should be same 
arr5= np.arange(0,10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr5.size

10

In [55]:
reshaped = arr5.reshape(2,5)
reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Transpose ##

In [57]:
arr6 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr6

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [59]:
arr6.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [60]:
transposed =np.transpose(arr6)
transposed

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

## Mathametical Operations

In [61]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

x+y

array([[ 6,  8],
       [10, 12]])

In [62]:
x-y

array([[-4, -4],
       [-4, -4]])

In [63]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [65]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [66]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [67]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [68]:
x//y

array([[0, 0],
       [0, 0]])

In [70]:
#elemenm wise multiplaciation
x*y

array([[ 5, 12],
       [21, 32]])

In [71]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [73]:
#MATRIX MULTIPLICATION
x@y

array([[19, 22],
       [43, 50]])

In [74]:
np.matmul(x,y)

array([[19, 22],
       [43, 50]])

# Create a fenced matrix for user using given shape where all corner elements are 1 rest all 0 

[[1 1 1 1], 
[1 0 0 1], 
[1 1 1 1]] 

#no of rows 

#no. of columns

In [78]:
m = int(input("Enter rows:"))
n = int(input("Enter cols:"))
arr7 = np.zeros((m,n),dtype = int)
arr7

Enter rows: 4
Enter cols: 4


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [81]:
arr7[0] = 1
arr7[:,0] = 1
arr7[:,-1] = 1
arr7[-1] = 1
arr7[0]
arr7

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

## Stacking

In [82]:
x=np.array([[1,2],[3,4]]) 
y=np.array([[5,6],[7,8]]) 
z=np.array([[9,10],[11,12]])

In [86]:
#horizontal stacking (side by side)
#no of rows has to be same otherwise wnt wor colm doesnot matter 
np.hstack((x,y,z))

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

In [87]:
np.vstack((x,y,z))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

Odd number of rows and columns

[[0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1], [0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0]]

https://drive.google.com/file/d/1L4M_a03yX1HY2vagDzSzQ1XFojYpnbng/view?usp=drive_link