In [2]:
import numpy as np
import pandas as pd

In [4]:
# 2d array with 8 elements - 1 to 8, find its dimension and its shape

In [10]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr.ndim

2

In [14]:
arr.shape

(2, 4)

In [16]:
# 2.
arr = np.array([
    [ 1,  2,  3,  4,  5,  6,  7],
    [ 8,  9, 10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19, 20, 21],
    [22, 23, 24, 25, 26, 27, 28],
    [29, 30, 31, 32, 33, 34, 35],
    [36, 37, 38, 39, 40, 41, 42],
    [43, 44, 45, 46, 47, 48, 49]
])
print(arr)
# How would you access the element `7` from this array?

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]


In [18]:
arr[0]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
arr[0][-1]

7

In [22]:
arr[0][6]

7

In [26]:
# On the same array, How would you access the element 47-49 from this array?

In [28]:
# 11:00 AM IST

In [30]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [36]:
arr[-1][4:]

array([47, 48, 49])

In [38]:
arr[6][4:7]

array([47, 48, 49])

In [40]:
arr[6][4:]

array([47, 48, 49])

In [42]:
arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
arr.shape

(2, 6)

In [44]:
# 12 elements -->
# 1)Reshape  this to 1x12 , tell me its dimnesion
# 2) Reshape this to 12x1 , tell me its dimnesion
# 3) 3x4, dimension
# 4) 4x3 dimension
# 5) 6x2, dimension

In [50]:
arr1_12 = arr.reshape(1,12)
arr1_12

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [70]:
arr1_12.ndim

2

In [54]:
arr12_1 = arr.reshape(12,1)
arr12_1

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [72]:
arr12_1.ndim

2

In [56]:
arr3_4 = arr.reshape(3,4)
arr3_4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
arr3_4.ndim

2

In [58]:
arr6_2 = arr.reshape(6,2)
arr6_2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [76]:
arr6_2.ndim

2

In [60]:
# flatten!

In [62]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [78]:
af = arr.flatten() #flatten the array & change it to 1d!
af

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [80]:
af.ndim

1

In [84]:
# 1. Create an array of zeros --> 3x3
# 2. Add 1 to its diagnol by using indexing!

In [90]:
arr0 = np.zeros((3,3))
arr0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [92]:
arr0[0][0] = 1

In [94]:
arr0

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [96]:
arr0[1][1] = 1
arr0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

In [98]:
arr0[2][2] = 1
arr0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [100]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [102]:
arr = np.array([5, 15, 25, 35, 10, 7])
arr
# Replace all values greater 
# than 10 in an array with 10?
# Expected output : [ 5 10 10 10 10 7]

array([ 5, 15, 25, 35, 10,  7])

In [106]:
arr

array([ 5, 15, 25, 35, 10,  7])

In [108]:
arr > 10 #bool outputs

array([False,  True,  True,  True, False, False])

In [112]:
arr[arr>10] #actual values which are greater than 10

array([15, 25, 35])

In [114]:
arr[arr>10] = 10 # replacevalues which are greater than 10 with 10

In [116]:
arr

array([ 5, 10, 10, 10, 10,  7])

In [118]:
# 1) Create a 1d array with elements 1-10
# 2) Extract all even numbers from a NumPy array
# o/p : array([ 2,  4,  6,  8, 10])
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
arr % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [128]:
arr[arr%2 == 0]

array([ 2,  4,  6,  8, 10])